<a href="https://colab.research.google.com/github/sandaruwanWGMA/Learn-Recommender-Systems/blob/main/User_User_Collaborative_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests

# The Google Sheets document ID from the URL
file_id = '1Moo1GrIu2K24kRZSS1QyLAkUXtUwiS3N'

# The URL for downloading the Excel file
url = f'https://docs.google.com/spreadsheets/d/{file_id}/export?format=xlsx'

# Make a request to the URL
response = requests.get(url)

# Save the content as an Excel file
with open('spreadsheet_data.xlsx', 'wb') as file:
    file.write(response.content)

In [3]:
import pandas as pd
data_sheet = pd.read_excel('spreadsheet_data.xlsx')
data_sheet.head()

,Unnamed: 0,1648,5136,918,2824,3867,860,3712,2968,3525,...,3556,5261,2492,5062,2486,4942,2267,4809,3853,2288
0,11: Star Wars: Episode IV - A New Hope (1977),NaN,4.5,5.0,4.5,4.0,4.0,NaN,5.0,4.0,...,4.0,NaN,4.5,4.0,3.5,NaN,NaN,NaN,NaN,NaN
1,12: Finding Nemo (2003),NaN,5.0,5.0,NaN,4.0,4.0,4.5,4.5,4.0,...,4.0,NaN,3.5,4.0,2.0,3.5,NaN,NaN,NaN,3.5
2,13: Forrest Gump (1994),NaN,5.0,4.5,5.0,4.5,4.5,NaN,5.0,4.5,...,4.0,5.0,3.5,4.5,4.5,4.0,3.5,4.5,3.5,3.5
3,14: American Beauty (1999),NaN,4.0,NaN,NaN,NaN,NaN,4.5,2.0,3.5,...,4.0,NaN,3.5,4.5,3.5,4.0,NaN,3.5,NaN,NaN
4,22: Pirates of the Caribbean: The Curse of the...,4.0,5.0,3.0,4.5,4.0,2.5,NaN,5.0,3.0,...,3.0,1.5,4.0,4.0,2.5,3.5,NaN,5.0,NaN,3.5

In [16]:
means_dict = {}
for column in data_sheet.columns[1:]:
    means_dict[column] = data_sheet[column].mean()

In [17]:
means_dict

{1648: 3.6515151515151514,
 5136: 4.107954545454546,
 918: 4.681818181818182,
 2824: 4.0588235294117645,
 3867: 3.6615384615384614,
 860: 3.6666666666666665,
 3712: 4.5,
 2968: 3.51010101010101,
 3525: 3.7135416666666665,
 4323: 4.041176470588235,
 3617: 4.065217391304348,
 4360: 3.859375,
 2756: 3.75974025974026,
 89: 4.397435897435898,
 442: 3.6,
 3556: 3.628205128205128,
 5261: 2.9642857142857144,
 2492: 3.44,
 5062: 3.8656716417910446,
 2486: 2.89,
 4942: 4.114864864864865,
 2267: 3.423076923076923,
 4809: 4.279411764705882,
 3853: 3.7,
 2288: 3.3698630136986303}